version: '3.8'

services:
  # O seu sistema de automação
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  # Banco de dados que seu .env já pede
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
